### ISSUE TITLE
姓氏.json may not have region-specific translations

### ISSUE THREAD

**Issue by BSBMteam** [Gowee/zhconv-rs#3]
This file has no region-specific translations. For example, some entries are perfect! Other entries just have one unspecified translation

Is this on purpose since 「于震」 can't be translated to 「於震」？

```
 {
      "original": null,
      "conv": "于娜"
    },
    {
      "original": null,
      "conv": "zh-hans:于荣光;zh-hant:于榮光"
    },
    {
      "original": null,
      "conv": "于震"
    },
    {
      "original": null,
      "conv": "zh-hans:于朦胧;zh-hant:于朦朧"
    },
```

**Comment by Gowee** [comment]
Yes. That is intended, I suppose.

**Comment by Gowee** [comment]
It turns out that I looked past such a kind of rule. The converter implementation doesn't process them properly. Fixing... 

Thanks for reporting.
